/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cdkbaterias.telas;
import br.com.cdkbaterias.dal.ModuloConexao;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Josias
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null;

    /**
     * Creates new form TelaPrincipal1
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        conexao = ModuloConexao.conector();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/background2.jpg"));
        Image image = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);

            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menCadUsu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menCadVend = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AlterarSucata = new javax.swing.JMenuItem();
        menuRel = new javax.swing.JMenu();
        relClientes = new javax.swing.JMenuItem();
        telaRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Sucata CDK BATERIAS");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        menuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/cadastro.png"))); // NOI18N
        menuCad.setText("Cadastro");
        menuCad.setToolTipText("Cadastros");

        menCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/IconCliente.png"))); // NOI18N
        menCadCli.setText("Cliente");
        menCadCli.setToolTipText("Cadastro Cliente");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        menuCad.add(menCadCli);
        menuCad.add(jSeparator5);

        menCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menCadUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/userIcon.png"))); // NOI18N
        menCadUsu.setText("Usuários");
        menCadUsu.setToolTipText("Cadastro Usuarios");
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        menuCad.add(menCadUsu);
        menuCad.add(jSeparator1);

        menCadVend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menCadVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/salesman.png"))); // NOI18N
        menCadVend.setText("Vendedor");
        menuCad.add(menCadVend);

        jMenuBar1.add(menuCad);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/sucata.png"))); // NOI18N
        jMenu3.setText("Sucatas");
        jMenu3.setToolTipText("Pedidos De Sucatas");

        AlterarSucata.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        AlterarSucata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/iconBattery2.png"))); // NOI18N
        AlterarSucata.setText("Controle Sucata");
        AlterarSucata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarSucataActionPerformed(evt);
            }
        });
        jMenu3.add(AlterarSucata);

        jMenuBar1.add(jMenu3);

        menuRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/Report.png"))); // NOI18N
        menuRel.setText("Relatório");
        menuRel.setToolTipText("Relatorios");

        relClientes.setText("Relatorio  Total de Clientes");
        relClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relClientesActionPerformed(evt);
            }
        });
        menuRel.add(relClientes);

        telaRelatorios.setText("Relatórios");
        telaRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaRelatoriosActionPerformed(evt);
            }
        });
        menuRel.add(telaRelatorios);

        jMenuBar1.add(menuRel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        setSize(new java.awt.Dimension(1386, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        // TODO add your handling code here:
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        Desktop.add(cliente);
    }//GEN-LAST:event_menCadCliActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        // As linhas a baixo chamam a tela usuario
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_menCadUsuActionPerformed

    private void AlterarSucataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarSucataActionPerformed
        // Chamando a tela alterar pedidos
        TelaAlterarPedidos AlterarSucata = new TelaAlterarPedidos();
        AlterarSucata.setVisible(true);
        Desktop.add(AlterarSucata);
    }//GEN-LAST:event_AlterarSucataActionPerformed

    private void relClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relClientesActionPerformed
        // Criando relatorio Clientes
        int confirma  = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório?","Atenção",JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {
            // imprimindo relatorio

            try {
                // usando classe jasperPrint para prepara a impressao de um relatorio

                JasperPrint print = JasperFillManager.fillReport("C:/reports/clientes.jasper",null,conexao);
                // a linha abaixo exibe o relatorio atraves da classe jasperview
                JasperViewer.viewReport(print,false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }

        }
    }//GEN-LAST:event_relClientesActionPerformed

    private void telaRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaRelatoriosActionPerformed
        TelaRelatorios telarelatorio = new TelaRelatorios();
        telarelatorio.setVisible(true);
        Desktop.add(telarelatorio);
    }//GEN-LAST:event_telaRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterarSucata;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenuItem menCadVend;
    public static javax.swing.JMenu menuCad;
    private javax.swing.JMenu menuRel;
    private javax.swing.JMenuItem relClientes;
    private javax.swing.JMenuItem telaRelatorios;
    // End of variables declaration//GEN-END:variables
}
