/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cdkbaterias.telas;

import java.sql.*;
import br.com.cdkbaterias.dal.ModuloConexao;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Josias
 */
public class TelaLogin extends javax.swing.JFrame {
    // usando a variavel conexao do dal
    Connection conexao = null;
    //criando variaveis especiais para conexão com o banco
    //prepared statement e resultSet sao frameworks do pacote java.sql
    //e servem apra preparar e executar instruçoes sql
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sql = "select * from usuarios1 where login=? and senha=?";
        try {
            //as linhas abaixo preparam a consulta ao banco em função do
            // que foi digitado nas caixas de texto. O ? é subistituido pelo
            //conteudo das variaves
            pst = conexao.prepareStatement(sql);
            pst.setString(1, c_usuario.getText());
            pst.setString(2, c_senha.getText());

            // a linha a baixo executa a query
            rs = pst.executeQuery();

            // se existir usuário e senha correspondente
            if (rs.next()) {
                // a linha abaixo obtem o conteudo do campo perfil da tabela tbusuario
                String perfil = rs.getString(5);
                // a estrutura abaixo faz o tratamento do perfil do usuário

                if (perfil.equals("admin")) {
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.menuCad.setEnabled(true);
                    
                    // a linha abaixo traz uma informaçao do banco de dados e
                    // seta ela em uma label no caso lblusuario
                    
                    // a linha abaixo seta uma cor a lbl escolhida
                    
                    this.dispose();
                }else{
                TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    
                    TelaPrincipal.menuCad.setEnabled(false);
                    // a linha abaixo traz uma informaçao do banco de dados e
                    // seta ela em uma label no caso lblusuario
                    
                    this.dispose();
                
                }
                conexao.close();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s)");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        c_usuario.setBorder(null);
        c_senha.setBorder(null);
        conexao = ModuloConexao.conector();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c_usuario = new javax.swing.JTextField();
        c_senha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE SUCATA");
        setBackground(new java.awt.Color(51, 255, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_usuario.setToolTipText("Informe seu usuário");
        c_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(c_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, 30));

        c_senha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(c_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 210, 30));

        btnLogin.setBackground(new java.awt.Color(204, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/botaoicon.PNG"))); // NOI18N
        btnLogin.setToolTipText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cdkbaterias/icones/ScreenLogin.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 600, 590));

        setSize(new java.awt.Dimension(563, 615));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Chamando o metodo logar
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void c_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_usuarioActionPerformed
        // TODO add your 
    }//GEN-LAST:event_c_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField c_senha;
    private javax.swing.JTextField c_usuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
